FROM ruby:2.6-alpine

RUN apk add --no-cache --update build-base chromium dpkg gcompat sqlite sqlite-dev tzdata
RUN gem install bundler

# App setup
WORKDIR /usr/src/app
COPY .. .
RUN bundle install

# Setup the entrypoint script
COPY extra/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
