name: linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run RuboCop
        uses: reviewdog/action-rubocop@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          rubocop_version: gemfile
          rubocop_extensions: rubocop-packaging:gemfile rubocop-performance:gemfile rubocop-rails:gemfile rubocop-rspec:gemfile

      - name: Run Fasterer
        uses: vk26/action-fasterer@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

      - name: Run Reek
        uses: reviewdog/action-reek@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
