---
name: Specs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bin/rspec --profile

      - name: On failure, store screenshots as artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-failed-screenshots
          path: spec/dummy/tmp/screenshots
